# Generated by Django 3.2.1 on 2021-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kuch',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
