# Generated by Django 3.2.1 on 2021-05-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_kuch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='kuch',
        ),
    ]
