# Generated by Django 3.2.1 on 2021-05-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Women', 'Women'), ('Men', 'Men'), ('Unisex', 'Unisex'), ('Kids', 'Kids')], max_length=50),
        ),
    ]
