# Generated by Django 3.2.1 on 2021-05-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Women', 'Women'), ('Men', 'Men'), ('Unisex', 'Unisex')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=None, max_length=500, upload_to='thumbnail/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(max_length=500, upload_to='product_images/'),
        ),
    ]
