# Generated by Django 3.2.1 on 2021-05-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('T-SHIRT', 'T-shirt'), ('SHIRT', 'Shirt'), ('JEANS', 'Jeans'), ('ACCESSORIES', 'Accessories')], default='S', max_length=50),
        ),
    ]
